sitetask/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('task.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

task/urls.py
from django.urls import path
from task import views

urlpatterns = [
    path('', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    ### - Задачи
    path('tasks/',    views.get_tasks, name='tasks'),
    path('tasks/add/', views.add_new_task, name='add_task'),
    path('tasks/<int:pk>/main/', views.get_task_main, name='view_task_main'),
    path('tasks/<int:pk>/chat/', views.get_task_chat, name='view_task_chat'),
    ### - Проекты
    path('projects/', views.GetProjects.as_view(), name='projects'),
    path('projects/add/', views.AddNewProject.as_view(), name='add_project'),
    path('projects/<int:pk>/main/', views.get_project_main, name='view_project_main'),
    path('projects/<int:pk>/tasks/', views.GetProjectTasks.as_view(), name='view_project_tasks'),
]

task/models.py
# import datetime
import locale
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField

locale.setlocale(locale.LC_ALL, 'ru_RU.UTF-8')

# from django.contrib.auth import get_user_model
# User = get_user_model()

FULL_USER_RIGHTS_ID = 1


def get_name(self):
    return f'{self.last_name} {self.first_name}'

User.add_to_class("__str__", get_name)

# Profile Details - Company, Job title, Department
# user_settings ???


class UserRoles(models.Model):
    title = models.CharField(max_length=50, verbose_name='Наименование')

    @property
    def is_full(self) -> bool:
        return self.id == FULL_USER_RIGHTS_ID

    def __str__(self) -> str:
        return self.title

    class Meta:
        db_table = 'task_user_roles'
        verbose_name = 'Роль пользователя'
        verbose_name_plural = 'Роли пользователей'
        ordering = ['title',]

class UserRights(models.Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name='Пользователь',
                             related_name='related_right')
    role = models.ForeignKey(UserRoles, on_delete=models.PROTECT, verbose_name='Роль',
                             related_name='related_right')

    def __str__(self):
        return self.role.title

    class Meta:
        db_table = 'task_user_rights'
        verbose_name = 'Права пользователя'
        verbose_name_plural = 'Права пользователей'
        ordering = ['user', 'role']

class Workspace(models.Model):
    title = models.CharField(max_length=100, verbose_name='Наименование')

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'task_workspace'
        verbose_name = 'Рабочее пространство'
        verbose_name_plural = 'Рабочие пространства'
        ordering = ['title']

class Department(models.Model):
    title = models.CharField(max_length=150, verbose_name='Наименование')
    workspace = models.ForeignKey(Workspace, on_delete=models.PROTECT, verbose_name='Рабочее пространство', related_name='related_department')

    def __str__(self):
        return f'{self.workspace.title} : {self.title}'

    class Meta:
        db_table = 'task_department'
        verbose_name = 'Подразделение'
        verbose_name_plural = 'Подразделения'
        ordering = ['workspace','title']

class WorkspaceMembers(models.Model):
    workspace = models.ForeignKey(Workspace, on_delete=models.PROTECT, verbose_name='Проект',
                                  related_name='related_workspace_members')
    user = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name='Участник',
                             related_name='related_workspace_members')

    def __str__(self):
        return f'{self.workspace.title} : {self.user.username}'

    class Meta:
        db_table = 'task_workspace_members'
        verbose_name = 'Участник пространства'
        verbose_name_plural = 'Участники пространства'
        ordering = ['workspace','user']

class ProjectStatus(models.Model):
    title = models.CharField(max_length=50, verbose_name='Наименование')

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'task_project_status'
        verbose_name = 'Статус проекта'
        verbose_name_plural = 'Статусы проекта'
        ordering = ['title']

class Project(models.Model):
    title = models.CharField(max_length=150, verbose_name='Наименование')
    # description = models.TextField(blank=True, verbose_name='Описание')
    description = RichTextUploadingField(blank=True, null=True, verbose_name='Описание')
    workspace = models.ForeignKey(Workspace, on_delete=models.PROTECT, verbose_name='Рабочее пространство',
                                  related_name='related_project')
    department = models.ForeignKey(Department, on_delete=models.PROTECT, verbose_name='Подразделение',
                                   related_name='related_project')
    owner = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name='Владелец',
                              related_name='related_project')
    status = models.ForeignKey(ProjectStatus, on_delete=models.PROTECT, verbose_name='Состояние',
                               related_name='related_project')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    finish_date = models.DateField(blank=True, null=True, verbose_name='Плановая дата выполнения')
    clousing_date = models.DateField(blank=True, null=True, verbose_name='Дата закрытия')


    def __str__(self):
        return self.title

    def get_absolute_url_main(self):
        return reverse('view_project_main', kwargs={"pk": self.pk})

    def get_absolute_url_tasks(self):
        return reverse('view_project_tasks', kwargs={"pk": self.pk})

    class Meta:
        db_table = 'task_project'
        verbose_name = 'Проект'
        verbose_name_plural = 'Проекты'
        ordering = ['created_at']

class ProjectMembers(models.Model):
    project = models.ForeignKey(Project, on_delete=models.PROTECT, verbose_name='Проект',
                                  related_name='related_project_members')
    user = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name='Участник',
                             related_name='related_project_members')

    def __str__(self):
        # return f'{self.project.title} : {self.user.username}'
        return self.project.title

    class Meta:
        db_table = 'task_project_members'
        verbose_name = 'Участник проекта'
        verbose_name_plural = 'Участники проекта'
        ordering = ['project', 'user']

class TaskStatus(models.Model):
    title = models.CharField(max_length=50, verbose_name='Наименование')

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'task_task_status'
        verbose_name = 'Статус задачи'
        verbose_name_plural = 'Статусы задачи'
        ordering = ['id']

class Task(models.Model):
    title = models.CharField(max_length=150, verbose_name='Наименование')
    # description = models.TextField(blank=True, verbose_name='Описание')
    description = RichTextUploadingField(blank=True, null=True, verbose_name='Описание')
    workspace = models.ForeignKey(Workspace, on_delete=models.PROTECT, verbose_name='Рабочее пространство',
                                  related_name='related_task')
    owner = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name='Владелец',
                             related_name='related_task_owner')
    executor = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name='Исполнитель',
                             related_name='related_task_executor')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    finish_date = models.DateField(blank=True, null=True, verbose_name='Плановая дата выполнения')
    status = models.ForeignKey(TaskStatus, on_delete=models.PROTECT, verbose_name='Состояние',
                             related_name='related_task')
    project = models.ForeignKey(Project, blank=True, null=True,  on_delete=models.PROTECT, verbose_name='Проект', related_name='related_task')
    department = models.ForeignKey(Department, on_delete=models.PROTECT, verbose_name='Подразделение',
                                   related_name='related_task')
    clousing_date = models.DateField(blank=True, null=True, verbose_name='Дата закрытия')

    def __str__(self):
        return self.title

    def get_absolute_url_main(self):
        return reverse('view_task_main', kwargs={"pk": self.pk})

    def get_absolute_url_chat(self):
        return reverse('view_task_chat', kwargs={"pk": self.pk})

    class Meta:
        db_table = 'task_task'
        verbose_name = 'Задача'
        verbose_name_plural = 'Задачи'
        ordering = ['created_at']

class TaskMembers(models.Model):
    task = models.ForeignKey(Task, on_delete=models.PROTECT, verbose_name='Задача',
                                  related_name='related_task_members')
    user = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name='Участник',
                             related_name='related_task_members')

    def __str__(self):
        return f'{self.task.title} : {self.user.username}'

    class Meta:
        db_table = 'task_task_members'
        verbose_name = 'Участник задачи'
        verbose_name_plural = 'Участники задачи'
        ordering = ['task', 'user']

class TaskFinishDateHistory(models.Model):
    task = models.ForeignKey(Task, on_delete=models.PROTECT, verbose_name='Задача',
                             related_name='related_task_finish_date_history')
    user = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name='Установил',
                             related_name='related_task_finish_date_history')
    finish_date = models.DateTimeField(verbose_name='Плановая дата выполнения')

    def __str__(self):
        return f'{self.task.title} : {self.user.name} : {self.finish_date}'

    class Meta:
        db_table = 'task_task_finish_date_history'
        verbose_name = 'История изменения плановой даты выполнения'
        verbose_name_plural = 'Истории изменения плановых дат выполнения'
        ordering = ['task', 'user', 'finish_date']

class TaskDispute(models.Model):
    task = models.ForeignKey(Task, related_name='related_task_dispute', on_delete=models.CASCADE, verbose_name='Задача')
    user = models.ForeignKey(User, related_name='related_task_dispute', on_delete=models.CASCADE, verbose_name='Автор')
    in_reply_task_dispute = models.IntegerField(blank=True, default=0, verbose_name='ID родительского сообщения')

task/templates/task/blank_main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Taskboard: Wrong side</title>
    <link rel="stylesheet" href="{% static 'css/style_item.css' %}"/>
    <link rel="icon" href="{% static 'icons/R-blue.png' %}" type="image/x-icon" width="16" height="16">
  </head>

  <body>

    {% include 'include/_header.html' %}

    <!-- MAIN -->

    <div class="container-fluid">
      <div class="row">
        <!-- SIDEBAR - START -->
        <nav
          id="sidebarMenu"
          class="col-md-3 col-lg-2 d-md-block bg-light taskboard_sidebar collapse">

          <div class="position-sticky sidebar-sticky ">

            <h6 class="taskboard_sidebar-heading d-flex justify-content-start align-items-center px-2 mt-3 mb-1 text-muted text-uppercase">
                <i class="bi bi-list" style="font-size: 1rem;"></i>
                <span class="taskboard_sidebar_heading">Разделы</span>
                <a class="link-secondary" href="#" aria-label="Add a new report">
                  <span data-feather="plus-circle" class="align-text-bottom"></span>
                </a>
            </h6>

            <ul class="list-unstyled fw-normal pb-2 small">
                <li><a href="" class="bd-links-link d-inline-block rounded active" aria-current="page" title="Основные данные задачи">Основные данные</a></li>
            </ul>

          </div>

        </nav>
        <!-- SIDEBAR - END -->

        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
          <div class="d-flex justify-content-center flex-wrap flex-md-nowrap align-items-center pt-2 mb-2 border-bottom">
            <h1 class="h4 text-danger">Вам здесь не рады!</h1>
          </div>
          <div class="d-flex justify-content-center pt-3">
            <img src="{% get_static_prefix %}{{ image_name }}" height="300" alt="Вам здесь не рады!">
          </div>
        </main>

      </div>
    </div>

    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

  </body>
</html>

task/templates/task/login.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" href="{% static 'icons/R-blue.png' %}" type="image/x-icon" width="16" height="16">
    <title>Taskboard</title>

    <link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/blocks/signin.css' %}">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
    </style>

  </head>
  <body class="text-center">
    
    <main class="form-signin w-100 m-auto">
      <form method="post">
        {% csrf_token %}
        <img class="mb-4" src="{% static 'icons/R-blue.png' %}" alt="" width="58" height="58">
        <h1 class="h3 mb-3 fw-normal">Пожалуйста, войдите</h1>

        <div class="form-floating">
          {{ form.username }}
          <label for="floatingInput">Адрес эл. почты</label>
        </div>
        <div class="form-floating">
          {{ form.password }}
          <label for="floatingPassword">Пароль</label>
        </div>

        <button class="w-100 btn btn-lg btn-primary" type="submit">Войти</button>
        <p class="mt-5 mb-3 text-muted"></p>

      </form>
    </main>
    
  </body>
</html>

task/templates/task/task_main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Taskboard: Главная страница задачи</title>
    <link rel="stylesheet" href="{% static 'css/style_item.css' %}"/>
    <link rel="icon" href="{% static 'icons/R-blue.png' %}" type="image/x-icon" width="16" height="16">
  </head>

  <body>

    {% include 'include/_header.html' %}

    <!-- MAIN -->

    <div class="container-fluid">
      <div class="row">
        <!-- SIDEBAR - START -->
        <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-none d-md-block bg-light taskboard_sidebar collapse">
          <div class="position-sticky sidebar-sticky">
            
            {% include 'include/_sidebar.html' %}
            
            <ul class="list-unstyled fw-normal pb-2 small">
              <li>
                <a href="{{ task_item.get_absolute_url_main }}" class="bd-links-link d-inline-block rounded active" 
                aria-current="page" title="Основные данные задачи">Основные данные</a></li>
              <li>
                <a href="{{ task_item.get_absolute_url_chat }}" class="bd-links-link d-inline-block rounded"  title="Перейти к обсуждению задачи">
                  Обсуждение
                  {% if new_messages > 0 %}
                  <text>(<b>+{{ new_messages }}</b>)</text>
                  {% endif %}
                </a>
              </li>
            </ul>

          </div>

        </nav>
        <!-- SIDEBAR - END -->       
          
        <main class="col-md-9 col-lg-10 px-md-2 taskboard_content">
          <form action="{% url 'view_task_main' task_item.pk %}" method="post">
            {% csrf_token %}            
            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-2 mb-1 border-bottom">
              <h1 class="h5">Задача: {{ task_item.title|truncatewords_html:7|safe }}</h1>
              <!-- "ЗАПИСАТЬ" ПОКАЗЫВАЕМ ТОЛЬКО НА БОЛЬШИХ ЭКРАНАХ -->

              <div class="btn-toolbar mb-1 d-none d-md-block">
              <button type="submit" class="btn btn-sm btn-outline-primary" id="save_new_form"
                    {% if input_right.button != True  %}
                    disabled
                    {% endif %}
                >Записать</button>
              </div>

            </div>
            <!-- ПАНЕЛЬ РАЗДЕЛОВ ДЛЯ СМАРТФОНОВ -->
            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-1 mb-2 d-md-none">
              <div class="btn-toolbar mb-2 mb-md-0">
                <a href="{{ task_item.get_absolute_url_main }}" class="bd-links-link-2 d-inline-block me-1 rounded active" aria-current="page" title="Основные данные задачи">Основные данные</a>
                <a href="{{ task_item.get_absolute_url_chat }}" class="bd-links-link-2 d-inline-block rounded" title="Перейти к обсуждению задачи">Обсуждение
                {% if new_messages > 0 %}
                <text>(<b>+{{ new_messages }}</b>)</text>
                {% endif %}
                </a>
              </div>
              <div class="btn-toolbar mb-2 mb-md-0">
                <button type="submit" class="btn btn-sm btn-outline-primary" id="save_new_form_mobile"
                {% if input_right.button != True %}
                disabled
                {% endif %}
                >
                  Записать
                </button>
              </div>
            </div>
            <div class="container-fluid">
              <div class="row">

                <!-- ФОРМА ЗАПОЛНЕНИЯ РЕКВИЗИТОВ ЗАДАЧИ  -->
                <div class="col-md-9 p-0">                  

                  <div class="mb-2">                    
                    <div class="d-flex justify-content-between">
                      <label for="{{ form.title.id_for_label }}" class="form-label">Наименование</label>
                      {% if task_item.clousing_date != Null %}
                      <span>Закрыта: {{ task_item.clousing_date|date:'d.m.Y' }}</span>
                      {% endif %}
                    </div>
                    <div class="form-control form-control-sm">
                    {{ task_item.title|safe }}
                    </div>
                  </div>

                  <div class="row align-items-start mb-2">
                    <div class="col pe-1">

                      <div class="col-md-12">
                        <label for="{{ form.workspace.id_for_label }}" class="form-label">Рабочее пространство</label>
                        <input
                              class="form-control form-control-sm"
                              id="id_workspace"
                              pk="{{ task_item.workspace.id }}"
                              value="{{ task_item.workspace|truncatewords:3|safe }}" disabled
                        />
                      </div>

                      <div class="col-md-12">
                        <label for="owner_area" class="form-label mt-2">Автор</label>
                        <input
                              class="form-control form-control-sm"
                              id="owner_area"
                              value="{{ task_item.owner }}" disabled
                        />
                      </div>

                      <div class="col-md-12">
                        <label for="{{ form.status.id_for_label }}" class="form-label mt-2">Состояние</label>
                        {% if input_right.status %}
                          {{ form.status }}
                        {% else %}
                          <input
                            class="form-control form-control-sm taskboard_form-fields"
                            id="id_status"
                            value="{{ task_item.status|safe }}" disabled
                          />
                        {% endif %}
                      </div>

                      <div class="col-md-12">
                        <label for="created_at_area" class="form-label mt-2">Дата создания</label>
                        <input
                            class="form-control form-control-sm"
                            type="date"
                            id="created_at_area"
                            value="{{ task_item.created_at|date:'Y-m-d' }}" disabled
                        />
                      </div>

                    </div>
                    
                    <div class="col ps-1">

                      <div class="col-md-12">
                        <label for="{{ form.department.id_for_label }}" class="form-label">Подразделение</label>

                        {% if input_right.department %}
                          {{ form.department }}
                        {% else %}
                          <input
                            class="form-control form-control-sm taskboard_form-fields"
                            id="id_department"
                            value="{{ task_item.department|safe }}" disabled
                          />
                        {% endif %}

                        {% if input_right.department %}
                          {% if form.department.errors %}
                            {% for error in form.department.errors %}
                            <div class="taskboard_invalid-feedback">
                                {{ error }}
                            </div>
                            {% endfor %}
                          {% endif %}
                        {% endif %}

                      </div>

                      <div class="col-md-12">
                        <label for="{{ form.executor.id_for_label }}" class="form-label mt-2">Исполнитель</label>
                        {% if input_right.executor %}
                          {{ form.executor }}
                        {% else %}
                          <input
                            class="form-control form-control-sm taskboard_form-fields"
                            id="id_executor"
                            value="{{ task_item.executor|safe }}" disabled
                          />
                        {% endif %}
                      </div>

                      <div class="col-md-12">

                        {% if task_item.project %}
                        <label for="{{ form.project.id_for_label }}" class="form-label mt-2"><a href="{% url 'view_project_main' task_item.project.pk %}" title="{{ task_item.project.title }}">Проект</a></label>
                        {% else %}
                        <label for="{{ form.project.id_for_label }}" class="form-label mt-2">Проект</label>
                        {% endif %}

                        {% if input_right.project %}
                          {{ form.project }}
                        {% else %}
                          <input
                            class="form-control form-control-sm taskboard_form-fields"
                            id="id_project"
                            {% if task_item.project %}
                            value="{{ task_item.project|truncatewords_html:6|safe }}"
                            title="{{ task_item.project.title }}"
                            {% endif %}
                            disabled
                          />
                        {% endif %}

                      </div>

                      <div class="col-md-12">
                        <label for="{{ form.finish_date.id_for_label }}" class="form-label mt-2">Планируемая дата выполнения</label>
                        {% if input_right.finish_date %}
                          {{ form.finish_date }}
                        {% else %}
                          <input
                            class="form-control form-control-sm"
                            type="date"
                            id="id_finish_date"
                            {% if task_item.finish_date %}
                            value="{{ task_item.finish_date|date:'Y-m-d' }}"
                            {% endif %}
                            disabled
                          />
                        {% endif %}
                      </div>
                    </div>
                  </div>

                  {% if task_item.description %}
                  <div class="mb-2">
                    <label for="{{ form.description.id_for_label }}" class="form-label">Описание</label>
                    <div class="form-control form-control-sm taskboard_form-fields">
                    {{ task_item.description|safe }}
                    </div>
                  </div>
                  {% endif %}

                </div>

                <!-- УЧАСТНИКИ -->
                <div class="col-md-3">
                  <div class="table-responsive">
                    <table class="table table-sm mb-2">
                      <thead>
                      <tr>
                        <th scope="col">Участники</th>
                        <th style="text-align: right">
                          {% if input_right.members %}
                            <button class="btn btn-light text-secondary border-0 taskboard_button_delete">
                              <i class="bi bi-download" style="font-size: 1rem; margin-right: 5px;" id="upload-members"
                                title="Заполнить участников из проекта"></i>
                            </button>
                          {% endif %}
                        </th>
                      </tr>
                      </thead>
                      <tbody id="participant-list">
                      </tbody>
                    </table>
                  </div>
                  {% if input_right.members %}
                    <div class="flex-fill">
                      {{ form_members.user }}
                    </div>
                    <div class="d-grid gap-2 mt-2">
                      <button type="button" id='members_add' class="btn btn-sm btn-outline-primary">Добавить</button>
                    </div>
                  {% endif %}
                </div>
              </div>
            </div>
          </form>
        </main>
      
      </div>
    </div>

    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/validation.js' %}"></script>
    <script src="{% static 'js/task_members.js' %}"></script>

  </body>
</html>